---
abstract: 'Access the DigitalOcean RESTful API (v2)'
author:
  - 'André Walker <andre@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: '6.30'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.019, CPAN::Meta::Converter version 2.140640'
license: gpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: WebService-DigitalOcean
provides:
  WebService::DigitalOcean:
    file: lib/WebService/DigitalOcean.pm
    version: '0.001'
  WebService::DigitalOcean::Role::DomainRecords:
    file: lib/WebService/DigitalOcean/Role/DomainRecords.pm
    version: '0.001'
  WebService::DigitalOcean::Role::Domains:
    file: lib/WebService/DigitalOcean/Role/Domains.pm
    version: '0.001'
  WebService::DigitalOcean::Role::Droplets:
    file: lib/WebService/DigitalOcean/Role/Droplets.pm
    version: '0.001'
  WebService::DigitalOcean::Role::UserAgent:
    file: lib/WebService/DigitalOcean/Role/UserAgent.pm
    version: '0.001'
requires:
  DateTime: '0'
  JSON: '0'
  LWP::UserAgent: '0'
  Moo: '0'
  Type::Tiny: '0'
  perl: '5.010'
resources:
  bugtracker: https://github.com/andrewalker/p5-webservice-digitalocean/issues
  repository: git://github.com/andrewalker/p5-webservice-digitalocean.git
version: '0.001'
